# Generated by Django 3.1.6 on 2021-11-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_customer_offer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='peko', max_length=225),
            preserve_default=False,
        ),
    ]
