# Generated by Django 3.1.6 on 2021-11-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211120_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Phone',
        ),
    ]
