# Generated by Django 3.1.6 on 2021-11-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
