# Generated by Django 3.1.6 on 2021-11-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='redeem_card',
            field=models.CharField(default='', max_length=20),
        ),
    ]
