# Generated by Django 3.1.6 on 2021-11-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ptype',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
