# Generated by Django 3.1.6 on 2021-11-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20211129_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
